title: Hafizuddin Norajame
email: hafiz.norajame@gmail.com
description: >-
 Hafiz Norajame
 Statistics enthuasiast
baseurl: "/"
url: "https://hafiznorajame.github.io"

header_pages:
 - blog.md
 - CV.md

theme: minima
plugins:
  - jekyll-feed

permalink: /blog/:title:output_ext

minima:
  date_format: "%-d %B %Y"

plugins:
  - jekyll-sitemap
