title: Hafiz Norajame
email: hafiz.norajame@gmail.com
description: >-
 Aspiring statistician
baseurl: "/"
url: "https://hafiznorajame.github.io"
github_username: hafiznorajame
linkedin_username: hafiz-norajame

header_pages:
 - blog.md
 - projects.md
 - CV.md

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /blog/:title:output_ext

minima:
  date_format: "%-d %B %Y"

plugins:
  - jekyll-sitemap
